### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [hilderonny/media-translator#1]
HELLO MAN...CONGRATULATIONS FOR YOUR AMAZING PROJECT!!!BUT COULD YOU PLEASE TELL ME STEP BY STEP WHAT I HAVE TO DO FOR USE YOUR AMAZING PROJECT?I AM NEW ON THIS AND I DONT KNOW!!!

**Comment by hilderonny** [comment]
Hi there,

first thank you for your interest. What do you want to do with the app? Do you simply need to use it or do you want to use the code in your own development?

If you want to use it, you can download the latest Release ZIP-file from https://github.com/hilderonny/media-translator/releases. Exteract it and run the "MediaTranslator.exe" file within it. On the first start the program needs to download some further data.

Sorry that the application is currently only in german.

To transcribe / translate a file, click on the "Datei auswählen ..." button and select a file (audio or video). Next choose a model size (small should be good for most purposes). and click on the "Transkription starten" button. (In the upcoming dialog click "Ok"). After some time of processing you should see the transcribed and translated results in the text field.

Best regards
Ronny
